run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 1m
  issues-exit-code: 1
  tests: true
  # list of build tags, all linters use it. Default is empty list.
  build-tags:
    - unit
  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - node_modules

# all available settings of specific linters
linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  nakedret:
    max-func-lines: 60

linters:
  enable:
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - interfacer
    - misspell
    - nakedret
    - scopelint
    - unconvert
    - unparam
  fast: false
